name: Nest Tests

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DB_URL: ${{ vars.DB_URL }}
      LOCALE: ${{ vars.LOCALE }}
      PORT: ${{ vars.PORT }}
      SECRET: ${{ vars.SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run tests e2e
        run: npm run test:e2e
